repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [ python ]
        additional_dependencies: ['pyright@latest']

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -vv --cov=atgql --cov-report term-missing
        language: system
        pass_filenames: false
